# Generated by Django 4.0.4 on 2022-05-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
