# Generated by Django 4.0.4 on 2022-05-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_account',
            field=models.BooleanField(default=False),
        ),
    ]
